#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# apps to not manage when they start
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^Fantastical$" manage=off
yabai -m rule --add app="^Parallels" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off

# apps fixed to a space
yabai -m rule --add app="^kitty$" space=1
yabai -m rule --add app="^Google Chrome$" space=2
yabai -m rule --add app="^Firefox" space=2
yabai -m rule --add app="^DataGrip$" space=3
yabai -m rule --add app="^DBeaver$" space=3
yabai -m rule --add app="^Navicat" space=3
yabai -m rule --add app="^Arc$" space=4
yabai -m rule --add app="^Notion$" space=5
yabai -m rule --add app="^Microsoft Teams" space=6
yabai -m rule --add app="^Slack" space=6
yabai -m rule --add app="^Todoist$" space=7
yabai -m rule --add app="^Spotify$" space=7

# https://github.com/FelixKratz/JankyBorders
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
