tap "felixkratz/formulae", trusted: true
tap "nikitabobko/tap", trusted: true
tap "noahgorstein/tap", trusted: true
tap "teamookla/speedtest", trusted: true

brew "bat"
brew "curl"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "htop"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "tree-sitter"
brew "neovim"
brew "node"
brew "pi-coding-agent"
brew "python@3.11"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "tree-sitter-cli"
brew "yq"
brew "zoxide"
brew "teamookla/speedtest/speedtest"

cask "nikitabobko/tap/aerospace"
cask "cmux"
cask "ghostty"
cask "kitty"
cask "zen"
